from __future__ import annotations
from typing import Any
from fpdf import FPDF


class AuditPDF(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42)
        self.rect(0, 0, 210, 27, "F")
        self.set_text_color(248, 250, 252)
        self.set_font("Helvetica", "B", 15)
        self.set_xy(14, 8)
        self.cell(0, 8, "BIS.SPEC  |  COMPLIANCE AUDIT", ln=1)
        self.set_font("Helvetica", "", 8)
        self.set_x(14)
        self.cell(0, 5, "PROCUREMENT SCREENING REPORT - NOT AN OFFICIAL BIS CERTIFICATE", ln=1)
        self.set_text_color(15, 23, 42)
        self.set_y(34)

    def footer(self):
        self.set_y(-13)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 8, f"Generated by BIS.SPEC | Page {self.page_no()}", align="C")


def generate_report(payload: dict[str, Any]) -> bytes:
    pdf = AuditPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Audit overview", ln=1)
    primary = payload.get("primary_recommendation") or {}
    standard = primary.get("standard", {})
    contractor = payload.get("contractor_view", {})
    _kv(pdf, "Generated", payload.get("generated_at", "Not recorded"))
    _kv(pdf, "Reference standard", standard.get("is_code", "No match"))
    _kv(pdf, "Domain", standard.get("domain", "-"))
    _kv(pdf, "Hybrid match", f"{primary.get('confidence', 0)}% ({primary.get('tier', '-')})")
    _kv(pdf, "Bid readiness", f"{contractor.get('bid_readiness_score', 0)}% - {contractor.get('verdict', '-')}")
    _section(pdf, "Extracted parameters")
    for key, values in payload.get("extracted_parameters", {}).items():
        _kv(pdf, key.replace("_", " ").title(), ", ".join(map(str, values)))
    _section(pdf, "Clause-by-clause matrix")
    rows = payload.get("compliance_matrix") or primary.get("compliance_matrix", [])
    if not rows:
        _multi(pdf, 6, "No clause matrix is available for this report.")
    for row in rows:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(241, 245, 249)
        _multi(pdf, 6, f"{row.get('clause_no', '')} - {row.get('parameter', '')} [{row.get('status', '')}]", fill=True)
        pdf.set_font("Helvetica", "", 8)
        _multi(pdf, 4.5, f"Tender: {row.get('tender_requirement', '')}")
        _multi(pdf, 4.5, f"Reference: {row.get('standard_spec', '')}")
        _multi(pdf, 4.5, f"Action: {row.get('action_required', '')}")
        pdf.ln(1)
    _section(pdf, "Actionable tender amendments")
    for amendment in payload.get("officer_view", {}).get("draft_tender_clauses", []):
        pdf.set_font("Helvetica", "B", 9)
        _multi(pdf, 5, amendment.get("section", ""))
        pdf.set_font("Helvetica", "", 8)
        _multi(pdf, 4.5, amendment.get("text", ""))
        pdf.ln(1)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(100, 116, 139)
    _multi(pdf, 4, "Reference clauses and QCO indicators in the embedded demo corpus are indicative. Verify current official BIS publications, QCO notifications, amendments, tender terms, and laboratory scope before reliance.")
    return bytes(pdf.output())


def _section(pdf: FPDF, title: str):
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(180, 83, 9)
    pdf.set_x(pdf.l_margin)
    pdf.cell(pdf.epw, 7, title, ln=1)
    pdf.set_text_color(15, 23, 42)


def _kv(pdf: FPDF, key: str, value: str):
    pdf.set_font("Helvetica", "B", 8)
    _multi(pdf, 5, key[:45])
    pdf.set_font("Helvetica", "", 8)
    _multi(pdf, 5, value)


def _multi(pdf: FPDF, height: float, text: str, **kwargs: Any):
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(pdf.epw, height, _safe(text), **kwargs)


def _safe(text: str) -> str:
    # Core PDF fonts are latin-1; preserve readable output without crashing on Indian scripts.
    return str(text).encode("latin-1", errors="replace").decode("latin-1")
